spring:
  application:
    name: configserver
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nikhilnpawar1411-art/project-config.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "M13Y8N14P99"

#        native:
#          search-locations: "classpath:/config"

server:
  port: 8071